# Generated by Django 3.0.8 on 2020-07-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(max_length=100, null=True)),
                ('primary_cancellation', models.URLField(max_length=1000, null=True)),
                ('secondary_cancellation', models.EmailField(max_length=100, null=True)),
            ],
        ),
    ]
