# Generated by Django 3.0.8 on 2020-07-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20200718_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='secondary_cancellation',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
